### PR TITLE
Enhance User and Admin Experiance

### PR DESCRIPTION
**Pull request by monagjr**
Hello,

Please review and accept this pull request which includes multiple experience enhancements for both frontend User and Admin.

- Replace the custom-built phone input UI with well-tested and production-ready UI from [International Telephone Input
](https://intl-tel-input.com/ ) which is sponsored by Twilio, integrates tons of features and customizations including integration of Google's libphonenumber for validation. it also has 6.4K stars on Github and more than 970,000 downloads/month on npm.js

- Enable Admin to select/enable only one country, if multiple countries share the same phone country code.
This happens by updating the underlying-code logic to use the standard iso country code as country selection value instead of country phone code.

-  Add option for Admin to control if the TOS checkbox should be checked by default or not.

- Add option for Admin to select the default selected Country in frontend.

- Empty phone placeholder in the frontend to show valid phone example for selected country instead of hard-coded text.

- Add option for Admin to add Custom CSS code.

- If phone is not provided in the frontend, or the TOS has not been checked, user gets clear error message for what's missing to accept his form input.

- The new integrated phone UI input has been even improved by enlarging its size to be more clear and easier for end-user.

### CODE REVIEW

**Comment by hamidalinia** [comment]
Hello, thanks my friend, I hope you be well, I will check and update on WordPress, Thank you

**Comment by hamidalinia** [comment]
I saw what you have done, many thanks, the flags and the UX is very good now، Soon I will merge cause we have developed some options, and we have to merge and check conflicts. I will name you in plugin page in WordPress and let you know, thanks.

**Comment by monagjr** [comment]
> I saw what you have done, many thanks, the flags and the UX is very good now، Soon I will merge cause we have developed some options, and we have to merge and check conflicts. I will name you in plugin page in WordPress and let you know, thanks.

Thank you for your feedback @idehweb , I appreciate your words and the mention in the plugin page in WordPress.
And I'm happy to know the contributions are helpful, and well received.

I'm also happy to know that you are adding new options 👍

To be fair, I'd like to get (Marshall Thomas @marshallthomas47) mentioned in the plugin page too, as he is the sponsor for this work.

Thanks!

**Comment by hamidalinia** [comment]
I have done your changes and pulled to github and WordPress plugin directory, thanks for your effort

**Review by hamidalinia — COMMENTED** [review]
thanks

**Comment by monagjr** [comment]
> I have done your changes and pulled to github and WordPress plugin directory, thanks for your effort

Thank you! and congratulations on the new release 🎉

Feel free to also add my Wordpress.org profile link to "Contributors & Developers" section here: https://wordpress.org/plugins/login-with-phone-number/

https://profiles.wordpress.org/mojr/

**Pull request closed without merging**
